#!/bin/bash

wallpaper="`fd . ~/Pictures/wallpapers -t f | shuf -n 1`"

cleaner=("konsole" "lxpolkit" "kdeconnect-indicator" "eww" "dunst" "gammastep" "kdeconnectd" "swww-daemon" "wl-paste" "nm-applet" "$HOME/.scripts/headphoned" "$HOME/.scripts/capsd")

for str in "${cleaner[@]}"
do
    kill -SIGTERM `pgrep -f "$str"`
done

swww-daemon --format xrgb &
swww img $wallpaper &
dunst &
lxpolkit &
gammastep -O 3500 &
kdeconnectd &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
wl-paste --primary --watch cliphist store &
kdeconnect-indicator &
konsole --background-mode &
nm-applet &
xhost + local: &
~/.scripts/capsd &
~/.scripts/headphoned &
eww open bar &
~/.scripts/ytrss update

