#!/usr/bin/env bash

. "$HOME/.local/lib/xlotus/xlfns"

BIN="$XLOTUS_BIN"

wallpaper="$(fd . ~/Pictures/wallpapers -t f | shuf -n 1)"

cleaner=("easyeffects" "foot" "lxpolkit" "kdeconnect-indicator" "eww" "dunst" "gammastep" "kdeconnectd" "swww-daemon" "wl-paste" "nm-applet")

for str in "${cleaner[@]}"
do
    kill -SIGTERM `pgrep -f "$str"`
done

swww-daemon --format xrgb &
swww img "$wallpaper" &
easyeffects --gapplication-service -l "Advanced Auto Gain" &
dunst &
lxpolkit &
gammastep -O 3500 &
kdeconnectd &
foot --server &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
wl-paste --primary --watch cliphist store &
kdeconnect-indicator &
nm-applet &
xhost + local: &
eww open bar &
"$BIN"/xl-yt -u
