#!/bin/bash

line=`cat ~/.cache/boatcfg/scripts/ytrss | grep --color=never -F ";;;$1"`

url=`echo "$line" | awk -F ';;;' '{print $5}'`
title=`echo "$line" | awk -F ';;;' '{print $4}'`
name=`echo "$line" | awk -F ';;;' '{print $2}'`

preview_height=`printf $(( $FZF_PREVIEW_LINES - 5 ))`
preview_width=`printf $(( $FZF_PREVIEW_COLUMNS - 5 ))`

curl -s "$url" | chafa -f sixels -s ${preview_width}x${preview_height} -
printf "[${name}]"
printf "$title" | bat --color=always \
        --style=grid \
        --wrap=auto \
        --terminal-width ${FZF_PREVIEW_COLUMNS}
