#!/usr/bin/env bash

# Using Konsole because both sixel and bidi are available
fterm () { konsole --notransparency -p tabtitle="Floating" -e "$@"; }
float_foot () { footclient --app-id="floating" -e "$@"; }


case $1 in
    sman) float_foot ~/.scripts/sman;;
    clip) fterm ~/.scripts/clipboard view;;
    search) fterm ~/.scripts/search;;
    rename) fterm ~/.scripts/extra/rename ${@:2};;
    rprop) float_foot "~/.config/river/scripts/riverprop";;
    fman) fterm "fileManager" lf;;
esac
