#!/bin/bash

source ~/.scripts/extra/cmdfns

process=`ps -e f | grep --color=never "https://stream.radiojar.com/8s5u5tpdtwzuv" | grep --color=never mpv | awk '{print $1}'`

case $1 in
    "play")
        if [ -z $process ]; then
            eww update quran_active=true 
            mpv --speed=1 https://stream.radiojar.com/8s5u5tpdtwzuv
        else
            notifier err \
                "CairoQuran" \
                "There's already a process running"
        fi
        ;;
    "stop")
        if [ -z $process ]; then
            notifier err \
                "CairoQuran" \
                "There's no process running to be stopped"
        else
            eww update quran_active=false
            kill $process
        fi
        ;;
    *)
        notifier invalid \
            "CairoQuran" \
            "$1" \
            "<b>Either 'play' or 'stop' was expected</b>"
        ;;
esac
