#!/bin/bash

source ~/.scripts/extra/cmdfns

[ ! -f $CACHE/pomo ] && mkdir -p $CACHE/pomo

function eww_reset () {
    [ -f $CACHE/pomo/"break" ] && rm $CACHE/pomo/"break"
    [[ $1 == "start" ]] && eww update pomo_pause=false
    eww update pomo_icon="󱎫"
    eww update pomo_break=false
    eww update rev_pomo=false
}

function escape () {
    case $1 in
        stop)
            duration=`cat $CACHE/pomo/duration`
            current=`cat $CACHE/pomo/current`
            elapsed="$(( $duration - $current ))"
            printf "%02d\n" $elapsed >> $CACHE/pomo/sessions
            eww_reset
            ;;

        finish) [ ! -f $CACHE/pomo/break ] && echo "$duration" >> $CACHE/pomo/sessions ;;
    esac
    rm $CACHE/pomo/{current,duration}
    echo "00:00" > $CACHE/pomo/log
}


function run () {

    duration=`cat $CACHE/pomo/duration`
    time="$duration"

    while true; do
        if [ $time -lt 0 ]; then
            escape finish
            if ! [ -f $CACHE/pomo/break ]; then
                eww update pomo_icon=""
                eww update pomo_break=true
                touch $CACHE/pomo/"break"
                notifier normal \
                    "folder-games" \
                    "Pomo" \
                    "Started break"
                duration="$(( $break_time*60 ))"
            else
                eww update pomo_icon="󱎫"
                eww update pomo_break=false
                rm $CACHE/pomo/"break"
                notifier normal \
                    "fcitx-handwriting-active" \
                    "Pomo" \
                    "Started working session"
                duration="$(( $working_time*60 ))"
            fi

            echo "$duration" > $CACHE/pomo/duration
            duration=`cat $CACHE/pomo/duration`
            time="$duration"
        fi

        min="$(( $time/60 ))"
        sec="$(( $time%60 ))"
        printf "%02d:%02d\n" $min $sec >> $CACHE/pomo/log
        time=$(( $time-1))
        echo "$time" > $CACHE/pomo/current
        sleep 1
    done
}

case $1 in
    start)
        if [ $# -eq 3 ]; then
            working_time=$2
            break_time=$3
        else
            working_time=25
            break_time=5
        fi

        process=`pgrep pomo`

        if ! [ -f $CACHE/pomo/current ] || [ $process -eq $$ ]; then
            eww_reset "start"
            duration="$(( $working_time * 60 ))"
            echo "$duration" > $CACHE/pomo/duration
            notifier normal \
                "fcitx-handwriting-active" \
                "Pomo" \
                "Started working session"
            touch $CACHE/eww/pomo.visible
            eww update rev_pomo=true
            run
        else
            notifier err \
                "Pomo" \
                "A session is already running"
        fi
        ;;

    pause) 
        eww update pomo_pause=true
        kill -STOP `pgrep pomo` 
        ;;

    resume) 
        eww update pomo_pause=false
        kill -CONT `pgrep pomo` 
        ;;

    stop) 
        notifier normal \
            "no" \
            "Pomo" \
            "Stopped timer"
        eww update rev_pomo=false 
        escape stop
        rm $CACHE/eww/pomo.visible
        kill -KILL `pgrep pomo`
        ;;
    *)
        notifier invalid \
            "Pomo" \
            "$1" \
            "<b>One of 'resume', 'pause', 'stop' and 'start' was expected</b>"
esac
