#!/bin/bash
#
# To be done:
# 1. Check state of wifi
# 2. If eth is connected disable wifi
# 3. notifications
#

source ~/.scripts/extra/cmdfns

function wifi () { doas wpa_cli -i $wifi_interface $@; }

eth_interface="eno1"
eth_state=`cat /sys/class/net/$eth_interface/operstate`

wifi_interface="wlo1"
wifi_state=`cat /sys/class/net/$wifi_interface/operstate`

case $1 in
    state)
        # Check if connection to router is available
        # Exit code 0 means connected
        ping -c 3 192.168.1.1
        echo $?
        ;;

    wifi)
        case $2 in
            state) echo "$wifi_state" ;;
            on) rfkill unblock wifi ;;
            off) rfkill block wifi ;;

            connect)
                wifi scan

                ssid=`wifi scan_results |\
                        cut -f5- |\
                        fzfcmd --prompt="Select Network > "`
                
                networkadded=`wifi list_networks |\
                                awk 'NR==3{print}'`

                if [ -z "$networkadded" ]; then
                    wifi add_network
                    wifi set_network 0 ssid '"'$ssid'"'
                    password=`fzfprompt "Password"`
                    wifi set_network 0 psk '"'$password'"'
                    unset password
                    wifi enable_network 0
                fi
                ;;

         esac
         ;;

     eth)
         case $2 in
             state) echo "$eth_state" ;;
         esac
         ;;

    *)
        notifier err \
            "dialog-error" \
            "Network" \
            "$1" \
            "<b>Either 'eth' or 'wifi' was expected</b>"
        ;;
esac
