#!/bin/bash
#
# This script is a modification of the script in this link: https://github.com/gojigeje/hijri.sh/blob/master/hijri.sh

source ~/.scripts/extra/cmdfns

function converter () {
    adjust=0

    gregYear="$3"
    gregMonth=`echo $2 | sed 's/^0*//'`
    gregDay=`date +%d -u -d "$3-$2-$1 $adjust day" | sed 's/^0*//'`

    # -----------------------------------------------------------------------------------
    # Calculation method below is pure magic to me ... I didn't manage to understand it
    # -----------------------------------------------------------------------------------
    # My understading so far is that it converts date like this
    # Gregorian => Julian => Hijri
    # -----------------------------------------------------------------------------------
    a=$(( ( gregMonth - 14 ) / 12 ))
    b=$(( ( gregYear + 4900 + a ) / 100 ))
    c=$(( ( 1461 * ( gregYear + 4800 + a ) ) / 4 ))
    d=$(( ( 367 * ( gregMonth - 2 - 12 * a ) ) / 12 ))
    e=$(( ( 3 * b ) / 4 ))
    jd=$(( c + d - e + gregDay - 32075 ))
    l=$(( jd - 1948440 + 10632 ))
    n=$(( ( l - 1 ) / 10631 ))
    l=$(( l - 10631 * n + 354 ))
    z=$(( ( ( 10985 - l ) / 5316 ) * ( ( 50 * l ) / 17719 ) + ( l / 5670 ) * ( ( 43 * l ) / 15238 ) ))
    l=$(( l - (( 30 - z ) / 15 ) * ( ( 17719 * z ) / 50 ) - ( z / 16 ) * ( ( 15238 * z ) / 43 ) + 29 ))
    m=$(( ( 24 * l ) / 709 ))
    d=$(( l - (( 709 * m ) / 24 ) ))
    y=$(( 30 * n + z - 30 ))
    # -----------------------------------------------------------------------------------

    lunarDay=$d
    lunarMonth=$m
    lunarYear=$y

    printf "%02d-%02d-%04d" "$lunarDay" "$lunarMonth" "$lunarYear"
}

lunarMonths=( "Muharram" "Safar" "Rabi Al-Awwal" "Rabi Al-Akhir" "Jumada Al-Awwal" "Jumada Al-Akhir" "Rajab" "Sha'ban" "Ramadan" "Shawwal" "Zul Qa'dah" "Zul Hijjah" )

dayNames=("Sat" "Sun" "Mon" "Tue" "Wed" "Thu" "Fri")
numOfMonths=`seq 1 12`
year=`date +%Y`

json=`jq --null-input "."`

for month in ${numOfMonths[@]}
do
    numOfDays=`date -u -d "$month/1 + 1 month - 1 day" +"%d"`
    dayRange=`seq 1 $numOfDays`

    firstHijriDate=`python $SCRIPTS/islamic/hijri.py 1 1 2024`
    firstHijriDayName=`python $SCRIPTS/islamic/hijri.py dayname greg 1 1 2024`

    firstHijriYear=`echo $firstHijriDate | awk -F '-' '{print $1}'`
    firstHijriMonth=`echo $firstHijriDate | awk -F '-' '{print $2}'`
    firstHijriDay=`echo $firstHijriDate | awk -F '-' '{print $3}'`
        
    firstHijriMonthPos=$((10#$firstHijriMonth - 1))
    firstHijriMonthName="${lunarMonths[$firstHijriMonthPos]}"

    firstHijriDayOrder=`echo ${dayNames[@]} |\
                sed 's/\s/\n/g' |\
                grep --color=never -n "${firstHijriDayName:0:3}" |\
                awk -F ':' '{print $1}'`

    loopOrder="$firstHijriDayOrder"
    loopWeekOrder=$(( firstHijriDay / 7 ))
    loopDayCounter=7

    if [ $month -eq 1 ]; then
        while [[ $loopWeekOrder -ge 0 ]]; do
            if [[ $loopWeekOrder -gt 0 ]]; then
                while [[ $loopDayCounter -gt 0 ]]; do
                    json=`echo $json | jq ".\"$firstHijriYear\".\"$firstHijriMonthName\".${dayNames[$loopDayCounter-1]}+=[\"\"]"`
                    loopDayCounter=$(( loopDayCounter - 1 ))
                done
            else
                while [[ $loopOrder -gt 1 ]]; do
                    json=`echo $json | jq ".\"$firstHijriYear\".\"$firstHijriMonthName\".${dayNames[$loopOrder-2]}+=[\"\"]"`
                    loopOrder=$(( loopOrder - 1 ))
                done
            fi
            loopWeekOrder=$(( loopWeekOrder - 1 ))
            [ $loopWeekOrder -gt 0 ] && loopDayCounter=7
        done
    fi

    for day in ${dayRange[@]}; do
        hijriDate=$(converter ${day} ${month} ${year})
        lunarDay=`echo $hijriDate | awk -F '-' '{print $1}'`
        lunarMonth=`echo $hijriDate | awk -F '-' '{print $2}'`
        lunarYear=`echo $hijriDate | awk -F '-' '{print $3}'`

        dayName=`date -u -d "${year}-${month}-${day} day" +"%a"`
        lunarMonthPos=$((10#$lunarMonth - 1))
        json=`echo $json | jq ".\"$lunarYear\".\"${lunarMonths[$lunarMonthPos]}\".$dayName+=[$lunarDay]"`
    done
    
    #last_day_order=`echo ${weekdays[@]} |\
    #            sed 's/\s/\n/g' |\
    #            grep --color=never -n "$lastDay" |\
    #            awk -F ':' '{print $1}'`

    #order="$(( last_day_order + 1))"
    #while [ $order -le 7 ]; do
    #    json=`echo $json | jq ".$monthName.${weekdays[$order-1]}+=[\"\"]"`
    #    order=$(( order + 1 ))
    #done
done


# jq --null-input -s '{"Day":"'$lunar_day'", "Month":"'"$lunar_month"'", "Year":"'$lunar_year'"}'
#printf "%s\n" "$json" | jq -M -c > $CACHE/cal/hijri_calendar
printf "%s\n" "$json" | jq 
