#!/bin/bash

source ~/.scripts/extra/cmdfns

PREVIEWER=~/.scripts/extra/fzfpreview

case $1 in
    view)
        choice="`cliphist list | fzfcmd "Clip" \
                             --preview-window=right:50% \
                             --preview=''$PREVIEWER' clip {}' \
                             --header="[alt-a => Autotype]" \
                             --bind="alt-a:become(~/.scripts/clipboard autotype {})"`"

        echo $choice

        if [ -n "$choice" ]; then
            printf "%s" "$choice" | cliphist decode | wl-copy
        fi
        ;;

    autotype)
        nohup bash -c "printf '%s' '${2}' | cliphist decode | wtype -s 150 - &" 2&>/dev/null
        ;;
esac

