#!/bin/bash
#
# This script is a modification of the script in this link: https://github.com/gojigeje/hijri.sh/blob/master/hijri.sh
# with some minor modifications
#
# date adjustment, use positive number to add days, negative number to substract, '0' for none.
adjust=0

day=`date +%d -d "$adjust day" | sed 's/^0*//'`
month=`date +%m | sed 's/^0*//'`
year=`date +%Y`

lunar_months=( "Muharram" "Safar" "Rabi Al-Awwal" "Rabi Al-Akhir" "Jumada Al-Awwal" "Jumada Al-Akhir" "Rajab" "Sha'ban" "Ramadhan" "Shawwal" "Zul Qa'dah" "Zul Hijjah" )

# -----------------------------------------------------------------------------------
# Calculation method below is pure magic to me ... I didn't manage to understand it
# -----------------------------------------------------------------------------------
a=$(( ( month-14 ) / 12 ))
b=$(( ( year+4900+a ) / 100 ))
c=$(( ( 1461*( year+4800+a ) ) / 4 ))
d=$(( ( 367 * ( month-2-12*a ) ) / 12 ))
e=$(( ( 3*b ) / 4 ))
jd=$(( c + d - e + day - 32075 ))
wd=$(( jd % 7 ))
l=$(( jd - 1948440 + 10632 ))
n=$(( ( l - 1 ) / 10631 ))
l=$(( l - 10631 * n + 354 ))
z=$(( ( ( 10985 - l ) / 5316 ) * ( ( 50 * l ) / 17719 ) + ( l / 5670 ) * ( ( 43 * l ) / 15238 ) ))
l=$(( l - (( 30 - z ) / 15 ) * ( ( 17719 * z ) / 50 ) - ( z / 16 ) * ( ( 15238 * z ) / 43 ) + 29 ))
m=$(( ( 24 * l ) / 709 ))
d=$(( l - (( 709 * m ) / 24 ) ))
y=$(( 30 * n + z - 30 ))
# -----------------------------------------------------------------------------------

lunar_day=$d
lunar_month_name=${lunar_months[$m-1]}
lunar_year=$y

printf "%02d %s %04dH\n" "$lunar_day" "$lunar_month_name" "$lunar_year"
