#!/bin/bash
#
# TODO: prevent overriding
# 
# Webcam:
# mpv --title="webcam" --geometry=640x480 --speed=1 --profile=low-latency --untimed --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg --script-opts=osc-visibility=never av://v4l2:/dev/video0

source ~/.scripts/extra/cmdfns

CACHE=~/.cache/dotfiles/shotcopy
TERMAN=~/.scripts/extra/terman

[ ! -d $CACHE ] && mkdir -p $CACHE

function menu () { $TERMAN rename "$@"; }

case $1 in
    "shot")
        case $2 in
            "copy")
                region=`slurp`
                if [ -n "$region" ]; then
                    grim -g "$region" - | wl-copy
                    notifier normal \
                        "folder-pictures" \
                        "Shotcopy: Screenshot (Copy)" \
                        "Copied to clipboard"
                fi
                ;;

            "region")
                region=`slurp`
                if [ -n "$region" ]; then 
                    grim -g "$region" $CACHE/screenshot.png
                    menu shot "Region"
                else
                    notifier normal \
                        "folder-pictures" \
                        "Shotcopy: Screenshot (Region)" \
                        "No region provided so didn't take screenshot"
                fi
                ;;

            "full")
                grim $CACHE/screenshot.png
                menu shot "Full"
                ;;
           
            *)
                notifier err \
                    "dialog-error" \
                    "Shotcopy: Screenshot" \
                    "$2" \
                    "<b>One of 'copy', 'region' or 'full' was expected</b>"
                ;;
        esac
        ;;


    "rec")
        # name of device below will be used as an audio source for screen recording
        device_name="alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"

        case $2 in
            "region")
                if [ -f $CACHE/recorder.lock ]; then
                    notifier normal \
                        "dialog-error" \
                        "Shotcopy: Recorder" \
                        "The script wasn't made to be run concurrently"
                else
                    region=`slurp`
                    if [ -n "$region" ]; then 
                        echo "Region" > $CACHE/recorder.lock

                        eww update rev_recording=true

                        wf-recorder -c libx264rgb               \
                                    --audio="$device_name"      \
                                    -g "$region"                \
                                    -f $CACHE/recording.mp4
                    fi
                fi
                ;;

            "full")
                if [ -f $CACHE/recorder.lock ]; then
                    notifier normal \
                        "dialog-error" \
                        "Shotcopy: Recorder" \
                        "The script wasn't made to be run concurrently"
                else
                    echo "Full" > $CACHE/recorder.lock

                    eww update rev_recording=true

                    wf-recorder -c libx264rgb               \
                                --audio="$device_name"      \
                                -f $CACHE/recording.mp4
                fi
                ;;

            "stop")
                if [ -f $CACHE/recorder.lock ]; then
                    kill -s SIGINT `pgrep wf-recorder`
                    eww update rev_recording=false
                    menu video
                else
                    notifier normal \
                        "dialog-error" \
                        "Shotcopy: Recorder" \
                        "Not even running to be stopped"
                fi
                ;;
            *)
                notifier err \
                    "dialog-error" \
                    "Shotcopy: Recorder" \
                    "$2" \
                    "<b>One of 'full', 'region' or 'stop' was expected</b>"
                ;;
        esac
        ;;
    *)
        notifier err \
            "dialog-error" \
            "Shotcopy" \
            "$1" \
            "<b>Either 'shot' or 'rec' was expected</b>"
        ;;
esac
