#!/bin/bash

step=5
muted=`pamixer --get-mute`

BARSCRIPTS=~/.scripts/bar

function update_eww () { eww update volume="`~/.scripts/bar/volume`"; }

case $1 in
    "down")
        if [ $muted == "false" ]; then 
		    pamixer -d $step
            update_eww
	    fi
        ;;
    "up")
        if [ $muted == "false" ]; then
		    pamixer -i $step
            update_eww
	    fi
        ;;
    "toggle")
	    pamixer -t
        update_eww
        ;;
esac

muted=`pamixer --get-mute`
volume=`pamixer --get-volume`


if [ $muted == "true" ]; then
    notify-send -r 101\
        "Muted" \
        -t 1000 \
        -i audio-volume-muted
else
    notify-send \
        -r 101 \
        "Volume  $volume%" \
        -t 1000 \
        -i audio-volume-high \
        -h int:value:$volume
fi
