#!/bin/bash

source ~/.scripts/extra/cmdfns

BINARY=~/.scripts/ytrss
YTSUBS=~/.scripts/data/ytsubs
CACHE=~/.cache/dotfiles/ytrss/
    
[ ! -f $YTSUBS ] && touch $YTSUBS

updater () {
    [ ! -f $CACHE/tmp ] && mkdir -p $CACHE/tmp
    # [ ! -f $CACHE/videotmp ] && mkdir -p $CACHE/videotmp
    rm $CACHE/tmp/*

    cat $YTSUBS |\
        awk -F ';;;' '{print $2}' |\
        sed 's/=/={/g; s/$/}/g' |\
        xargs -P 0 -I {} curl -X 'GET' -s {} --output $CACHE/tmp/'#1'

    if [ $? -ne 0 ]; then
        notifier normal \
                 "dialog-error" \
                 "Ytrss" \
                 "Cannot fetch feed, There seems to be a network error"
        exit 1
    fi

    cat $CACHE/tmp/* |\
            awk '/<entry>/,/<\/entry>/' |\
            grep --no-group-separator --color=never -A 10 href |\
            sed '/author>/d; /<uri>/d; /<media:group>/d; /<media:content url=/d; /<updated>/d; s/.*href="//g; s/.*<media:thumbnail url="//g; s/".*$//g; s/.*<published>//g; s/<\/published>.*$//g; s/^.*<media:title>//g; s/<\/media:title>.*$//g; s/&quot;/"/g; s/^.*<name>//g; s/<\/name>.*$//g; s/&amp;/\&/g' |\
            perl -pe 's/\n/;;;/g if $. % 5' |\
            awk -F ';;;' '{t=$1; $1=$3; $3=t; print $1";;;"$2";;;"$3";;;"$4";;;"$5;}' > $CACHE/ytrss
    
    #    
    # Fetching video duration (Commented because it didn't work properly)
    #
    #cat $CACHE/ytrss |\
    #        awk -F ';;;' '{print $3}' |\
    #        sed 's/?v=/?v={/g; s/$/}/g' |\
    #        xargs -P 0 -I {} curl -s -X 'GET' "{}" --output $CACHE/videotmp/'#1'
    #
    # grep -F '<meta itemprop="duration"' ~/.cache/boatcfg/scripts/videotmp/* |\
    # sed 's/^.*content="PT//g; s/".*$//g; s/M/:/g; s/S//g' > ~/.cache/boatcfg/scripts/videotmp/duration

    # paste -d\; ~/.cache/boatcfg/scripts/ytrss-tmp ~/.cache/boatcfg/scripts/videotmp/duration > ~/.cache/boatcfg/scripts/ytrss

    notifier normal \
        "application-rss+xml" \
        "Ytrss" \
        "Feed updated successfully"
}

case $1 in
    view)
        if ! [ -f $CACHE/ytrss ]; then
            clear
            echo "Updating feed..."
            updater
        fi

        choice=`cat $CACHE/ytrss |\
            sort -r |\
            awk -F ';;;' '{ printf "%s\n", $4}' |\
            fzfcmd "Video" \
                   --preview-window=right:50% \
                   --bind="focus:transform-header(~/.scripts/ytrss fzfheader {}),alt-s:become(~/.scripts/ytrss fzflink browser {}),alt-c:execute(~/.scripts/ytrss fzflink copy {})" \
                   --preview="~/.scripts/extra/fzfpreview ytrss {}"`

        choiceUrl=`grep -F ";;;$choice" $CACHE/ytrss | awk -F ';;;' '{print $3}'`

        if [ -n "$choice" ]; then
            nohup bash -c "source ~/.scripts/extra/cmdfns; mpvcmd $choiceUrl &" 2&>/dev/null
        fi
        ;;

    fzflink)
            shift
            url=`grep -F ";;;$2" $CACHE/ytrss | awk -F ';;;' '{print $3}'`
            if [[ -n $url ]]; then
                case $1 in
                    browser)
                        nohup bash -c "firefox \"${url}\" &" 2&>/dev/null
                        ;;
                    copy)
                        printf "%s" "$url" | wl-copy
                        ;;
                esac
            fi
        ;;

    fzfheader)
        if [[ -n "${@:2}" ]]; then
            grep -F ";;;${@:2}" $CACHE/ytrss |\
                sed 's|$HOME/.cache/boatcfg/scripts/ytrss:||g' |\
                awk -F ';;;' '{printf "[ Upload: %s ]\n[alt-s => Firefox][alt-c => Copy]" ,$1 }'
        else
            printf "[alt-s => Firefox][alt-c => Copy]"
        fi
        ;;

    update)
        updater
        ;;

    add)
        yturl=`wl-paste`
        if [ -n "$yturl" ]; then
            if [[ $yturl =~ ^"https://www.youtube.com/@" ]]; then
                rssinfo=`curl -s "$yturl" | grep '{"title":' | sed 's/.*{"channelMetadataRenderer"://g; s/{"title"://g; s/","description":.*,"rssUrl":"/;;;/g; s/",".*//g; s/^.*"//g; s/channel_id=UC/playlist_id=UU/g'`
                
                $BINARY ytrssCheckUrl add "$rssinfo" "$yturl"
            else
                notifier err
                    "Ytrss" \
                    "Not a youtube url" \
                    "<b>Please copy the url of a youtube channel to your clipboard</b>"
            fi
        fi
        ;;

    import)
        cat $2 |\
            jq ".subscriptions[] | .url, .name" |\
            sed 's|^"http.*channel/UC|https://www.youtube.com/feeds/videos.xml?playlist_id=UU|g; s/^"//g ;s/"$//g' |\
            perl -pe 's/\n/;;;/g if $. % 2' |\
            awk -F ';;;' '{t=$1; $1=$2; $2=t; print $1";;;"$2}' |\
            xargs -n1 -I {} bash -c "$BINARY ytrssCheckUrl import '{}'" 2&>/dev/null

        notifier normal \
            "application-rss+xml" \
            "Ytrss" \
            "Imported successfully"
        ;;

    ytrssCheckUrl)
        case $2 in
            add)
                if grep -q -w "^$3$" $YTSUBS; then
                    notifier err \
                        "Ytrss" \
                        "Feed already exists"
                else
                    echo "$3" >> $YTSUBS
                    notifier normal \
                        "application-rss+xml" \
                        "Ytrss" \
                        "Feed added successfully" \
                        "<b>$4</b>"
                fi
                ;;
            import)
                if ! grep -q -w "^$3$" $YTSUBS; then
                    echo "$3" >> $YTSUBS
                fi
                ;;
        esac
        ;;

    export)
        if [ -n "$2" ]; then
            cat $YTSUBS |\
                awk -F ';;;' '{t=$1; $1=$2; $2=t; print $1";;;"$2}' |\
                sed 's/^/{\n"service_id": 0,\n"url": "/g; s/;;;/",\n"name": "/g; s/$/"\n}/g; s|feeds/videos.xml?playlist_id=UU|channel/UC|g' |\
                jq -s '{"app_version": "0.27.0", "app_version_int": 997, "subscriptions": .}' > $2.json
        else
            notifier normal \
                "dialog-error" \
                "Ytrss" \
                "Please name the exported file"
        fi
        ;;
    *)
        notifier invalid \
            "Ytrss" \
            "$1" \
            "<b>One of 'view', 'update', 'add' or 'import' was expected</b>"
esac
